Repository grafbase/opentelemetry-datadog-cloudflare, pull requests merged in 2023-03, with the labels that each got.

#72 Revert "1.0.0"
  CHANGELOG.md
  Cargo.toml
Labels: Action: no bump

#71 Async export
  CHANGELOG.md
  Cargo.toml
  src/exporter/mod.rs
  src/lib.rs
Labels: Action: beta bump

#73 fix cargo publish
  CHANGELOG.md
  Cargo.toml
  src/exporter/mod.rs
Labels: Action: minor bump

#74 Swap the `surf` client out for `reqwest` and drop unused dependencies (including worker)
  .github/workflows/ci.yml
  .github/workflows/deployment.yml
  CHANGELOG.md
  Cargo.toml
  README.md
  build.rs
  rust-toolchain.toml
  src/exporter/mod.rs
  src/exporter/model/mod.rs
  src/lib.rs
Labels: Action: minor bump
